'use client';
import { useEffect, useRef, useState } from 'react';
import { flushSync } from 'react-dom';
type Run = { lane:number; score:number; lives:number; elapsed:number; spawn:number; items:{lane:number;z:number;good:boolean}[] };
const fresh=():Run=>({lane:1,score:0,lives:3,elapsed:0,spawn:0,items:[]});
export default function Home(){
 const canvas=useRef<HTMLCanvasElement>(null), board=useRef<HTMLDivElement>(null), run=useRef(fresh());
 const [mode,setMode]=useState<'ready'|'playing'|'paused'|'over'>('ready');
 const [hud,setHud]=useState({score:0,lives:3,time:30});
 const bursts=useRef<{lane:number;good:boolean;age:number}[]>([]), audio=useRef<AudioContext|null>(null), master=useRef<GainNode|null>(null), enabled=useRef(true);
 const [sound,setSound]=useState(true);
 const unlock=()=>{try{if(!audio.current){audio.current=new AudioContext();master.current=audio.current.createGain();master.current.gain.value=enabled.current?.16:0;master.current.connect(audio.current.destination)}void audio.current.resume().catch(()=>{})}catch{}};
 const blip=(good:boolean)=>{const a=audio.current,bus=master.current;if(!enabled.current||!a||!bus||a.state!=='running')return;[...(good?[784,1047,1568]:[180,95,48])].forEach((hz,i)=>{const o=a.createOscillator(),g=a.createGain(),t=a.currentTime+i*.055;o.type=good?'square':'sawtooth';o.frequency.setValueAtTime(hz,t);if(!good)o.frequency.exponentialRampToValueAtTime(hz*.45,t+.14);g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(.3,t+.004);g.gain.exponentialRampToValueAtTime(.001,t+.15);o.connect(g);g.connect(bus);o.start(t);o.stop(t+.16);o.onended=()=>{o.disconnect();g.disconnect()}})};
 const toggleSound=()=>{enabled.current=!enabled.current;setSound(enabled.current);unlock();if(master.current&&audio.current)master.current.gain.setTargetAtTime(enabled.current?.16:0,audio.current.currentTime,.01);try{localStorage.setItem('signal-run-sound',String(enabled.current))}catch{}};
 useEffect(()=>{try{enabled.current=localStorage.getItem('signal-run-sound')!=='false';setSound(enabled.current)}catch{}return()=>{void audio.current?.close().catch(()=>{});audio.current=null;master.current=null}},[]);
 const start=()=>{unlock();bursts.current=[];run.current=fresh();setHud({score:0,lives:3,time:30});setMode('playing');board.current?.focus({preventScroll:true})};
 const move=(d:number)=>{run.current.lane=Math.max(0,Math.min(2,run.current.lane+d))};
 useEffect(()=>{const context=(document as Document & {modelContext?:{registerTool:(tool:{name:string;description:string;inputSchema:object;annotations:object;execute:(input:unknown)=>unknown},options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;if(!context)return;const lifecycle=new AbortController();try{Promise.resolve(context.registerTool({name:'start_signal_run',description:'Start or restart the visible 30-second Signal Run game. Resets score and lives.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw new Error('Expected an empty object');flushSync(()=>start());return {status:'playing',score:0,lives:3,time:30}}},{signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort()},[]);
 useEffect(()=>{const c=canvas.current;if(!c)return;const ctx=c.getContext('2d');if(!ctx)return;let frame=0,last=0;const reduced=window.matchMedia('(prefers-reduced-motion: reduce)');
 const draw=(now:number)=>{const dt=last?Math.min((now-last)/1000,.04):0;last=now;const w=c.clientWidth,h=c.clientHeight,dpr=Math.min(devicePixelRatio||1,2);if(c.width!==Math.round(w*dpr)||c.height!==Math.round(h*dpr)){c.width=Math.round(w*dpr);c.height=Math.round(h*dpr)}ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);const r=run.current;
 if(mode==='playing'){r.elapsed+=dt;r.spawn+=dt;if(r.spawn>.62){r.spawn=0;r.items.push({lane:Math.floor(Math.random()*3),z:0,good:Math.random()>.32})}for(const item of r.items){item.z+=dt*(.42+r.elapsed*.004);if(item.z>=.91&&item.z<2){if(item.lane===r.lane){if(item.good)r.score+=100;else r.lives--;bursts.current.push({lane:item.lane,good:item.good,age:0});blip(item.good)}item.z=3}}r.items=r.items.filter(i=>i.z<2);setHud({score:r.score,lives:Math.max(0,r.lives),time:Math.max(0,Math.ceil(30-r.elapsed))});if(r.elapsed>=30||r.lives<=0)setMode('over')}
 if(mode!=='paused')for(const b of bursts.current)b.age+=dt;bursts.current=bursts.current.filter(b=>b.age<.8);
 ctx.save();const impact=bursts.current.find(b=>!b.good&&b.age<.24);if(impact&&!reduced.matches){const strength=5*(1-impact.age/.24);ctx.translate(Math.sin(impact.age*110)*strength,Math.cos(impact.age*95)*strength)}
 const point=(x:number,z:number)=>({x:w/2+x*(w*.105+z*w*.35),y:h*.12+z*z*h*.75});ctx.lineWidth=1;
 for(let i=0;i<4;i++){const x=-1+i*2/3,a=point(x,0),b=point(x,1);ctx.strokeStyle=i===0||i===3?'#baff2966':'#ffffff25';ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke()}
 for(let i=0;i<=12;i++){const z=(i/12+(mode==='playing'?r.elapsed*.25:0))%1,a=point(-1,z),b=point(1,z);ctx.strokeStyle='#ffffff20';ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke()}
 const items=mode==='ready'?[{lane:0,z:.6,good:true},{lane:2,z:.36,good:false},{lane:1,z:.2,good:true}]:r.items;
 for(const item of items){const p=point((item.lane-1)*2/3,item.z),s=6+item.z*16;ctx.save();ctx.translate(p.x,p.y);ctx.strokeStyle=item.good?'#baff29':'#ff6d83';ctx.lineWidth=2;if(item.good){ctx.rotate(Math.PI/4);ctx.strokeRect(-s/2,-s/2,s,s)}else{ctx.beginPath();ctx.moveTo(-s/2,-s/2);ctx.lineTo(s/2,s/2);ctx.moveTo(s/2,-s/2);ctx.lineTo(-s/2,s/2);ctx.stroke()}ctx.restore()}
 const p=point((r.lane-1)*2/3,.92);ctx.fillStyle='#baff29';ctx.shadowColor='#baff29';ctx.shadowBlur=22;ctx.beginPath();ctx.moveTo(p.x,p.y-14);ctx.lineTo(p.x+21,p.y+12);ctx.lineTo(p.x,p.y+5);ctx.lineTo(p.x-21,p.y+12);ctx.closePath();ctx.fill();ctx.shadowBlur=0;
 for(const b of bursts.current){const origin=point((b.lane-1)*2/3,.91),life=1-b.age/.8,color=b.good?'#baff29':'#ff6d83';ctx.save();ctx.strokeStyle=color;ctx.fillStyle=color;ctx.globalAlpha=life;ctx.lineWidth=2;ctx.shadowColor=color;ctx.shadowBlur=reduced.matches?0:12;
 if(!reduced.matches){ctx.beginPath();ctx.arc(origin.x,origin.y,12+b.age*(b.good?95:125),0,Math.PI*2);ctx.stroke();for(let i=0;i<24;i++){const angle=i/24*Math.PI*2,travel=(45+(i%5)*22)*b.age;ctx.save();ctx.translate(origin.x+Math.cos(angle)*travel,origin.y+Math.sin(angle)*travel+b.age*b.age*65);ctx.rotate(b.age*(i%2?5:-5));if(b.good){ctx.fillStyle=i%3===0?'#ffffff':color;ctx.fillRect(-2,-2,4+life*2,4+life*2)}else{ctx.beginPath();ctx.moveTo(-5,-2);ctx.lineTo(4,2);ctx.stroke()}ctx.restore()}}
 ctx.shadowBlur=0;ctx.font='bold 17px monospace';ctx.textAlign='center';ctx.fillText(b.good?'+100':'−1 LIFE',origin.x,origin.y-30-(reduced.matches?0:b.age*45));ctx.restore()}
 ctx.restore();frame=requestAnimationFrame(draw)};frame=requestAnimationFrame(draw);const hide=()=>{if(document.hidden&&mode==='playing')setMode('paused')};document.addEventListener('visibilitychange',hide);return()=>{cancelAnimationFrame(frame);document.removeEventListener('visibilitychange',hide)}},[mode]);
 return <main><header className="nav"><a href="#" aria-label="MadAboutSoftware home"><img src="/logo.png" alt="MadAboutSoftware"/></a><nav><a href="#games">Our games ↗</a><a href="https://linkedin.com/in/crmp" target="_blank" rel="noreferrer">Let’s talk ↗</a></nav></header>
 <section className="hero"><div className="intro"><p className="eyebrow"><i/> INDEPENDENT MINDS. PLAYFUL WORLDS.</p><h1>Seriously<br/>mad about<br/><em>play.</em></h1><p className="lede">Sharp product intuition.<br/>An obsession with a great game.<br/>That’s MadAboutSoftware.</p><a className="text-link" href="#games">Discover our games <span>↓</span></a><div className="side-note">PRODUCT THINKING × GAME MAKING</div></div>
 <div className="arcade" ref={board} tabIndex={0} role="region" aria-label="Signal Run game. Move with left and right arrows or A and D. P pauses." onKeyDown={e=>{if(mode!=='playing'&&mode!=='paused')return;if(['ArrowLeft','ArrowRight','a','d','p','P'].includes(e.key))e.preventDefault();if(mode==='playing'){if(e.key==='ArrowLeft'||e.key==='a')move(-1);if(e.key==='ArrowRight'||e.key==='d')move(1)}if(e.key.toLowerCase()==='p')setMode(mode==='paused'?'playing':'paused')}}>
 <div className="game-top"><span><i/> LAB / 001</span><span>30 SECONDS. ALL INSTINCT.</span></div><div className="game-title"><h2>SIGNAL<br/><span>RUN</span></h2><p>Catch the signal.<br/>Dodge the noise.</p></div><div className="hud"><div>SCORE<strong>{String(hud.score).padStart(4,'0')}</strong></div><div>TIME<strong>{hud.time}s</strong></div><div>LIVES<strong>{'●'.repeat(hud.lives)}{'○'.repeat(3-hud.lives)}</strong></div></div>
 <canvas ref={canvas} aria-label="Three lane playfield. Catch green diamonds for 100 points. Pink crosses cost one life."/>
 {mode!=='playing'&&<div className={`game-overlay ${mode==='ready'?'initial':''}`}>{mode==='over'&&<><p className="eyebrow">{hud.lives>0?'RUN COMPLETE':'OUT OF SIGNAL'}</p><h3>{hud.score.toLocaleString()} <small>PTS</small></h3><p>{hud.score>=2000?'Sharp instincts. Nice run.':'One more run? Trust your instincts.'}</p></>}{mode==='paused'&&<h3>Take a breath.</h3>}<button className="play-button" onClick={()=>mode==='paused'?setMode('playing'):start()}>{mode==='ready'?'LET’S PLAY':mode==='paused'?'RESUME RUN':'PLAY AGAIN'} <span>↗</span></button>{mode==='ready'&&<p className="game-hint">Catch ◇ · Avoid × · Three lives. Make them count.</p>}</div>}
 <div className="game-bottom"><div className="controls"><button aria-label="Move left" disabled={mode!=='playing'} onClick={()=>move(-1)}>←</button><button aria-label="Move right" disabled={mode!=='playing'} onClick={()=>move(1)}>→</button><span>ARROWS / A D / TAP</span></div><button className="pause sound-toggle" aria-label="8-bit sound" aria-pressed={sound} onClick={toggleSound}>{sound?'♪ ON':'♪ OFF'}</button><button className="pause" disabled={mode==='ready'||mode==='over'} onClick={()=>setMode(mode==='paused'?'playing':'paused')}>{mode==='paused'?'RESUME':'PAUSE Ⅱ'}</button></div><p className="sr-only" aria-live="polite">{mode==='over'?`Run finished. Score ${hud.score}.`:mode==='paused'?'Game paused.':''}</p></div></section>
 <div className="ticker"><span>BUILT ON INSTINCT.</span><b>✳</b><span>MADE TO BE PLAYED.</span><b>✳</b><span>BUILT ON INSTINCT.</span><b>✳</b><span>MADE TO BE PLAYED.</span></div>
 <section id="games" className="games"><div className="section-heading"><p className="eyebrow">01 / THE GAMES</p><h2>Find your next<br/><em>rabbit hole.</em></h2><p>Different worlds.<br/>The same obsession with play.</p></div><div className="game-cards"><a className="portfolio skipper" href="https://skippers.gg" target="_blank" rel="noreferrer"><div className="card-meta">MADABOUTSOFTWARE / 01 <span>↗</span></div><div className="wordmark">Skippers<span>↗</span></div><div className="card-footer"><span>Explore the game</span><span>SKIPPERS.GG ↗</span></div></a><a className="portfolio lore" href="https://lorebound.gg" target="_blank" rel="noreferrer"><div className="card-meta">MADABOUTSOFTWARE / 02 <span>↗</span></div><div className="wordmark">Lorebound<span>✳</span></div><div className="card-footer"><span>Enter the world</span><span>LOREBOUND.GG ↗</span></div></a></div></section>
 <section className="about"><p className="eyebrow">02 / BEHIND THE PLAY</p><div><h2>A game is a product.<br/><span>A great one makes<br/>you feel something.</span></h2><p>MadAboutSoftware is an independent mobile gaming studio and product management advisory. Behind it: a veteran product manager who has built software used by tens of thousands of small businesses and enterprise software users.</p><p>That experience shapes every game—and every product conversation.</p><a className="text-link" href="https://linkedin.com/in/crmp" target="_blank" rel="noreferrer">Meet the mind behind the games ↗</a></div></section><footer><p>Have a good feeling<br/>about this? <a href="https://linkedin.com/in/crmp" target="_blank" rel="noreferrer">Let’s talk ↗</a></p><div><span>© {new Date().getFullYear()} MadAboutSoftware</span><span>GREAT PRODUCTS. SERIOUS PLAY.</span><a href="#">BACK TO TOP ↑</a></div></footer></main>
}
